// Auto-gerado: mapeamento slug de transcricao -> URL do YouTube
// Fonte: canal @brunopellizzetti (UCUYbn1lwf_EKh36Ew9jneow)
// Gerado em: 2026-04-20T14:35:38.874723

export const YT = {
  "YT-2018-08-10-Tutorial_-_Como_pesquisar_Jurisprudencia_Previdenciaria_no_TRF4": "https://youtu.be/e59TfVLlZ5Y",
  "YT-2020-12-08-Bruno_Responde_-_Como_funciona_a_aposentadoria_do_deficiente": "https://youtu.be/2bbC2D6hzzY",
  "YT-2021-02-02-A_importancia_do_recolhimento_previdenciario_para_o_beneficiario_do_LOAS_BPC_que_tem_dependentes": "https://youtu.be/yCeAPA8sVXI",
  "YT-2021-02-12-Aposentadoria_especial_do_servidor_publico_da_saude_-_Regime_proprio_IPMC_e_outros": "https://youtu.be/mu_trm21voc",
  "YT-2021-02-18-Por_que_todos_devem_contribuir_com_o_INSS": "https://youtu.be/Dovp6UKrZwQ",
  "YT-2021-02-25-Regra_do_Descarte_aposentadoria_apos_Reforma_da_Previdencia_EC_103_2019": "https://youtu.be/i7N8tYaruRw",
  "YT-2021-02-26-TESE_DO_DESCARTE_MAXIMO_-_O_maior_furo_do_INSS_dos_ultimos_tempos": "https://youtu.be/3uA5f7kcUjM",
  "YT-2021-03-09-15_dicas_sobre_o_Auxilio-acidente": "https://youtu.be/SpfyAVmeS98",
  "YT-2021-03-11-Revisao_do_LOAS_BPC_-_Convertendo_em_aposentadoria_por_invalidez": "https://youtu.be/23UlQDreb90",
  "YT-2021-03-18-Aposentadoria_do_Professor_no_RPPS": "https://youtu.be/HJP1MUdIk-I",
  "YT-2021-03-23-Aposentadoria_Especial_pos_Reforma_da_Previdencia": "https://youtu.be/4JezkvG6pi0",
  "YT-2021-03-25-E_possivel_acumular_a_pensao_por_morte_com_minha_aposentadoria": "https://youtu.be/aqHRZiHN2iY",
  "YT-2021-04-06-CASO_PRATICO_-_aposentadoria_do_Professor_servidor_publico": "https://youtu.be/r1Jf7Dq0ed8",
  "YT-2021-04-16-15_dicas_sobre_pensao_por_morte": "https://youtu.be/srnUWth7uUk",
  "YT-2021-04-20-Aposentadoria_-_180_contribuicoes_ou_15_anos": "https://youtu.be/spKM7H3WMCs",
  "YT-2021-04-27-Passo_a_passo_do_requerimento_de_pensao_por_morte": "https://youtu.be/D9Bfvgpep8g",
  "YT-2021-05-07-Saiba_tudo_sobre_a_Lei_de_indenizacao_para_vitimas_do_enfrentamento_da_COVID-19": "https://youtu.be/GwUcDTwaymo",
  "YT-2021-05-11-Agencia_do_INSS_fechada_Conheca_as_novas_regras_da_Portaria_Conjunta_32_de_31_de_Marco_de_2021": "https://youtu.be/AnYL3jbJoTU",
  "YT-2021-05-20-Manual_da_Aposentadoria_por_Idade_Urbana_-_INSS": "https://youtu.be/TFjXNTMSLoA",
  "YT-2021-05-27-LOAS_BPC_-_5_dicas_para_evitar_o_pente_fino_do_INSS": "https://youtu.be/T_kEX2IH7sw",
  "YT-2021-06-01-FAKE_NEWS_-_Visao_monocular_e_o_direito_a_aposentadoria_por_invalidez": "https://youtu.be/wuCU7MM3qkA",
  "YT-2021-06-11-Entrevista_com_o_cliente_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "https://youtu.be/bSrhNUY8m34",
  "YT-2021-06-15-Pensao_por_morte_para_o_homem_a_partir_da_Constituicao_Federal_de_1988_-_VITORIA_E_IGUALDADE": "https://youtu.be/lrQbMKk1KN4",
  "YT-2021-06-24-O_que_fazer_quando_o_INSS_demora_para_analisar_um_beneficio": "https://youtu.be/dTwEe3JhhZc",
  "YT-2021-07-15-Analise_e_conferencia_CNIS_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "https://youtu.be/E-FRr1yTv08",
  "YT-2021-07-20-Os_direitos_previdenciarios_do_Autista_TEA": "https://youtu.be/UzMWi-zkyc8",
  "YT-2021-07-27-Estou_gravida._Tenho_direito_ao_salario-maternidade": "https://youtu.be/f4qLI7Zoe5E",
  "YT-2021-08-03-Como_funciona_a_regra_dos_pontos_do_INSS": "https://youtu.be/t4fXGfV_Woo",
  "YT-2021-08-13-Tudo_o_que_voce_precisa_saber_sobre_Salario_Maternidade": "https://youtu.be/hbG97CwwgTc",
  "YT-2021-08-17-Aposentadoria_do_servidor_publico_-_agente_penitenciario_DEPEN": "https://youtu.be/9OVQxNRYaXs",
  "YT-2021-08-24-5_dicas_para_evitar_fraudes_contra_aposentados_e_pensionistas": "https://youtu.be/O34XBzMbaf0",
  "YT-2021-09-02-Pensao_por_morte_e_irretroatividade": "https://youtu.be/Q5qMdA9M4xE",
  "YT-2021-09-08-A_acao_mais_dificil_do_direito_previdenciario": "https://youtu.be/GT8LoNZ1kew",
  "YT-2021-09-14-Busca_de_documentos_comprobatorios_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "https://youtu.be/SLn0sYWYI7w",
  "YT-2021-09-22-Posso_acumular_mais_de_um_beneficio_do_INSS": "https://youtu.be/rBCVWxtxYTw",
  "YT-2021-09-28-Sou_MEI_microempreendedor_individual_posso_me_aposentar": "https://youtu.be/L8uJ8W_UVBE",
  "YT-2021-10-28-Como_complementar_as_contribuicoes_previdenciarias_do_MEI_e_baixa_renda_para_Aposentadoria": "https://youtu.be/1c5oaMZV7NE",
  "YT-2021-11-24-Servidor_publico_pode_ter_empresa": "https://youtu.be/CwgOH1bMDTI",
  "YT-2021-11-30-A_inconstitucionalidade_da_NOVA_Pensao_por_Morte": "https://youtu.be/IORqUFj3qSM",
  "YT-2023-01-12-Mudancas_no_auxilio_reclusao": "https://youtu.be/yN-QFXP35vA",
  "YT-2023-01-14-Aprenda_a_criar_uma_conta_Gov.br_de_forma_rapida_e_facil": "https://youtu.be/Q5Refh-8b_w",
  "YT-2023-01-15-Tutorial_de_como_acessar_os_dados_do_CNIS_e_qual_sua_utilidade": "https://youtu.be/DEi4E5Z2IcY",
  "YT-2023-01-17-Tutorial_-_Como_acessar_a_Revisao_da_Vida_Toda_-_Carta_de_Concessao_pelo_portal_Meu.INSS": "https://youtu.be/I2oD3lpmba0",
  "YT-2023-01-18-Tutorial_-_Requerimento_do_Auxilio-Doenca_em_2023_de_forma_gratuita_online_e_rapida": "https://youtu.be/VXD9MCzIM7s",
  "YT-2023-02-10-Como_recolher_contribuicao_em_atraso_sendo_ADVOGADO": "https://youtu.be/kHyWQHKDm4U",
  "YT-2023-02-28-Analise_do_caso_pratico_de_Aposentadoria_por_Idade_com_tempo_de_servico_miitar._PARTE_1.": "https://youtu.be/j9-AgxWQjGk",
  "YT-2023-03-28-Como_ajustar_o_codigo_de_recolhimento_do_INSS_ajuste_de_guias_erro_de_recolhimento": "https://youtu.be/JhOH-NcqIm0",
  "YT-2023-05-17-Escritorio_de_Advocacia_e_advogado_-_Passo_a_passo_do_simples_Nacional_-_parte_1_-_Pedido_inicial": "https://youtu.be/1b7XVN44tHA",
  "YT-2023-05-19-Aposentadoria_e_Auxilio_Doenca_para_portador_de_HIV_-_Doencas_Estigmatizantes": "https://youtu.be/jxbFMjRa1J4",
  "YT-2023-05-23-Escritorio_de_Advocacia_e_advogado_-_Passo_a_passo_do_simples_Nacional_-_parte_2_-_Apos_Deferimento": "https://youtu.be/7PcbL4pwUIk",
  "YT-2023-05-30-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P3_Preenchimento_Empresa_Facil": "https://youtu.be/mszxTlbaHow",
  "YT-2023-06-02-Tutorial_-_Requerimento_da_Aposentadoria_por_Idade_em_2023_de_forma_gratuita_online_e_rapida": "https://youtu.be/fGtCSft6ikg",
  "YT-2023-06-06-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P4_Contrato_Social": "https://youtu.be/688w0lMwYzE",
  "YT-2023-06-08-Aposentadoria_e_Auxilio_Doenca_para_quem_tem_Bipolaridade_-_Doencas_Estigmatizantes": "https://youtu.be/IzkM6eERID0",
  "YT-2023-06-13-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_P5_Conferencia_Final_e_Documentos": "https://youtu.be/08DudS4312o",
  "YT-2023-06-15-Aposentadoria_Especial_-_Para_Dono_de_Posto_de_Combustiveis": "https://youtu.be/kyhssY3TnoM",
  "YT-2023-06-20-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P6_-_Opcao_Pelo_Simples": "https://youtu.be/EJ5HAWhkZuU",
  "YT-2023-06-22-Pensao_por_Morte_Rural_em_2023_-_Como_solicitar_de_forma_rapida_e_gratuita.": "https://youtu.be/8eF0lnIpSaU",
  "YT-2023-06-27-Pensao_por_morte_para_filho_nao_nascido_-_O_que_voce_precisa_saber": "https://youtu.be/_KcjSsxDU6c",
  "YT-2023-06-29-Decisao_Injusta_-_Impactos_da_Sumula_111_no_Direito_Previdenciario": "https://youtu.be/XhMP8-sbSLA",
  "YT-2023-07-04-Aposentadoria_Especial_em_Postos_de_Combustivel_-_Decisao_Importante_do_INSS": "https://youtu.be/Jv9bMPRWtXc",
  "YT-2023-07-04-Aposentadoria_e_Auxilio_Doenca_para_portador_de_Cancer_de_Pele._Doencas_Estigmatizantes": "https://youtu.be/qvUsUl6Jz8s",
  "YT-2023-07-11-Acesso_aos_Laudos_Medicos_-_Descubra_o_Motivo_do_Indeferimento_em_2023": "https://youtu.be/hIo5CwzQuQk",
  "YT-2023-07-13-Problemas_com_a_Simulacao_do_Meu_INSS_-_Caso_Real": "https://youtu.be/exHe3TjqI5I",
  "YT-2023-07-18-Tripla_Acumulacao_de_Beneficio_-_O_Polemico_Debate_que_Afeta_Pensionistas": "https://youtu.be/jPWrd8rW-nY",
  "YT-2023-08-01-Aposentadoria_e_Auxilio_Doenca_para_portador_de_Esquizofrenia._Doencas_Estigmatizantes": "https://youtu.be/xVWaiHB2MB4",
  "YT-2023-08-03-Tutorial_-_Como_Elaborar_uma_Peticao_Inicial_de_Incapacidade_em_2023": "https://youtu.be/hEgCjUwDMsY",
  "YT-2023-08-22-Novidades_no_Tema_1019_do_STF_-_Vitoria_pela_Integralidade_dos_Policiais_Civis_-_RPPS": "https://youtu.be/onRwKoid9eY",
  "YT-2023-08-25-Tutorial_Como_Regularizar_Contribuicoes_Abaixo_do_Minimo_Legal": "https://youtu.be/Y0P22NtWGcY",
  "YT-2023-08-29-As_5_grandes_mentiras_sobre_Aposentadoria_do_INSS": "https://youtu.be/38ebbX8CTy8",
  "YT-2023-08-31-Valor_da_Aposentadoria_por_Invalidez_menor_Auxilio_Doenca_do_INSS._Entenda_essa_regra_prejudicial": "https://youtu.be/9We0W_dyDSM",
  "YT-2023-09-05-Aposentadoria_Especial_do_Coveiro_-_Caso_Real_-_Vitoria_do_Caso._RPPS": "https://youtu.be/klso4F_MCio",
  "YT-2023-09-12-O_Que_NAO_Fazer_na_SUA_Pericia_Medica_do_INSS_5_Dicas_para_Conseguir_sua_Aprovacao": "https://youtu.be/yl6FdDJhA2k",
  "YT-2023-09-14-4_ERROS_que_Podem_Atrapalhar_sua_Aposentadoria_-_Descubra_o_que_o_INSS_nao_te_contou": "https://youtu.be/Cz8jLZBAaDI",
  "YT-2023-09-19-Desvendando_a_Nova_Aposentadoria_-_3_Regras_de_Transicao_que_VOCE_Precisa_Conhecer_no_INSS": "https://youtu.be/xjppMIaFD4w",
  "YT-2023-09-26-Como_pedir_sua_Aposentadoria_por_Idade_em_2023_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/nN7-0ch5lz4",
  "YT-2023-09-29-Aposentadoria_Especial_do_Eletricista_-_Aprenda_como_ler_e_corrigir_o_PPP_igual_ao_INSS_e_a_Justica": "https://youtu.be/tTb9BQizERc",
  "YT-2023-10-03-Aposentadoria_Especial_do_Pedreiro_Como_Conseguir_a_Aposentadoria_e_Melhorar_seu_Valor": "https://youtu.be/ITR5lHPppG4",
  "YT-2023-10-10-Aposentado_e_Pensionista_no_Exterior_Desconto_de_25%_FIXO_Para_Quem_Mora_no_Exterior_Tema_1174_STF": "https://youtu.be/OIGAh7QnrVg",
  "YT-2023-10-19-Lei_259_de_2023_PR_Nova_Carreira_Escrivao_e_Agente_Policia_Civil_O_que_fazer_Servidor_e_Aposentado": "https://youtu.be/5zdR8jElJjc",
  "YT-2023-10-24-Decisao_TCE_PR_pode_salvar_aposentadoria_e_abono_servidor_publico_PRPREV_LC_233_21_e_EC_45_2019": "https://youtu.be/8zXWT4ppdMM",
  "YT-2023-10-26-Um_erro_do_INSS_que_poderia_ter_custado_caro_para_uma_empregada_publica_da_CEF": "https://youtu.be/-YJyxvfSiPw",
  "YT-2023-11-01-Duplo_Pedagio_para_Aposentadoria_Integralidade_e_Paridade_do_Policial_e_Seguranca_Publica_Parana": "https://youtu.be/EN128NiIN6g",
  "YT-2023-11-14-Entenda_tudo_sobre_revisao_de_Aposentadoria_e_Pensao_no_RPPS": "https://youtu.be/FVgsy8N06PU",
  "YT-2023-11-17-Tutorial_ePROTOCOLO_Parana_-_Como_Cadastrar_Cadastro_Inicial_parana": "https://youtu.be/puWffRNop-8",
  "YT-2023-11-22-Tutorial_ePROTOCOLO_Parte_2_-_Como_fazer_um_requerimento_simples_Por_exemplo_CTC": "https://youtu.be/wO8bnuyZNKg",
  "YT-2023-11-24-Servidor_Publico_pode_abrir_MEI_Confira_esse_e_outros_questionamentos_do_RPPS_relacionado_ao_INSS": "https://youtu.be/XneooU5UQo8",
  "YT-2023-12-01-Entenda_a_restricao_da_Triplice_Acumulacao_de_Beneficios_e_cargos_servidores_publicos_no_TCU_RPPS": "https://youtu.be/CXLdYQXx1DI",
  "YT-2023-12-04-Previdencia_Complementar_Parana_-_Como_vai_funcionar_a_aposentadoria_para_os_novos_servidores": "https://youtu.be/QbugU9Zkqww",
  "YT-2023-12-12-Auxilio_Acidente_no_MEI_-_Um_beneficio_que_tem_sido_esquecido": "https://youtu.be/h8iuyvUhzJg",
  "YT-2024-02-15-Revisao_da_Aposentadoria_e_Pensao_no_Teto_Maximo_e_Teto_Minimo_Atualmente_direitoprevidenciario": "https://youtu.be/sSvvOdWw9Mo",
  "YT-2024-02-27-Aposentadoria_especial_do_FRENTISTA_e_do_CAIXA_postodecombustivel": "https://youtu.be/-s7pvJaAGcU",
  "YT-2024-02-29-Pedido_de_Aposentadoria_Especial_negado_com_muitos_erros_aprenda_como_corrigir_com_essa_estrategia": "https://youtu.be/4C9GgU3P_to",
  "YT-2024-03-01-Entrevista_com_o_Dr.Calc_Eduardo_Teixeira_Maggi": "https://youtu.be/NK5M0F2jE4E",
  "YT-2024-03-01-Trailer_do_Canal": "https://youtu.be/XuIldEG-cXw",
  "YT-2024-03-08-Como_pedir_seu_auxilio_doenca_em_2024_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/swo_mah8K2Y",
  "YT-2024-03-08-Como_pedir_sua_Aposentadoria_por_Idade_em_2024_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/XjSsuqdNyiM",
  "YT-2024-03-12-Aposentadoria_Negada_Indeferida_-_Enfermeiras_e_Auxiliar_de_Enfermagem_-_O_que_fazer": "https://youtu.be/GYxHm_BpS8Y",
  "YT-2024-04-03-Aposentadoria_Especial_do_MOTORISTA_-_Uma_batalha_perdida": "https://youtu.be/xMf_vwzOSGg",
  "YT-2024-04-03-Como_pedir_DESISTENCIA_de_Beneficio_em_2024_pelo_MEU_INSS": "https://youtu.be/BepzzLjw86I",
  "YT-2024-04-23-Aposentei_pelo_INSS_SEM_averbar_o_tempo_rural_e_agora_Revisao_do_Tempo_Rural": "https://youtu.be/FjSzHkno4jw",
  "YT-2024-05-07-Posso_pagar_o_INSS_em_atraso_para_me_aposentar": "https://youtu.be/MNrSvM-etZg",
  "YT-2024-05-09-Aposentadoria_do_Deficiente_Apos_a_Reforma_da_Previdencia_EC_103_2019_Entenda_a_Disputa_dos_80x100": "https://youtu.be/-JXd8oK1D0o",
  "YT-2024-05-13-Visao_Monocular_-_Uma_Rediscussao_EQUIVOCADA_da_Lei_Amalia_Barros_-_LEI_14.126_de_2021": "https://youtu.be/A1-Hq1U5ooo",
  "YT-2024-05-15-Aposentadoria_do_Trabalhador_Rural_em_2024_-_Guia_Completo_do_Segurado_Especial_-_O_que_nao_fazer": "https://youtu.be/wOavXhSUJn8",
  "YT-2024-05-21-Como_analisar_sua_carta_de_CONCESSAO_do_meu_INSS_de_forma_simples_e_rapida": "https://youtu.be/NiWfoXs_GAs",
  "YT-2024-05-23-Aposentadoria_Especial_do_Vigilante_-_Mais_um_Direito_Na_Mira_do_STF_-_Tema_1209": "https://youtu.be/Vwy-k96wN7Q",
  "YT-2024-06-06-Como_criei_um_Robo_para_responder_perguntas_diarias_usando_Llamaindex_+_WhatsApp_+_ChatGPT": "https://youtu.be/UdTFBhCOlwA",
  "YT-2024-06-17-Como_funciona_a_APOSENTADORIA_da_pessoa_com_Deficiencia_no_RPPS": "https://youtu.be/CIkvRY4o184",
  "YT-2024-06-18-Tema_810_STF_-_A_Vitoria_do_IPCA_e_a_AINDA_possivel_revisao_de_Previdenciarios_e_Precatorios_INSS": "https://youtu.be/kdBaazBkrAY",
  "YT-2024-06-20-O_que_acontece_quando_mudo_meu_regime_previdenciario_como_servidor_publico_Entenda_migracao_de_CTC": "https://youtu.be/oUQS5ja3Dac",
  "YT-2024-06-25-Advogado_-_Entenda_como_conseguir_a_Ajuda_do_Juiz_para_resolver_questoes_dificeis_nos_seus_processos": "https://youtu.be/M0xgOd78F9M",
  "YT-2024-06-27-Serie_CTC_e_RPPS_-_O_que_nao_fazer_quando_voce_esta_proximo_de_se_aposentar_no_Regime_Publico": "https://youtu.be/ywoYy0eXwBg",
  "YT-2024-07-02-Serie_CTC_e_RPPS_-_O_servidor_pode_recolher_sua_contribuicao_em_atraso_-_Entenda_esse_caso_na_licenca": "https://youtu.be/IoZz7zImc2w",
  "YT-2024-07-04-Serie_CTC_e_RPPS_-_Averbacao_e_Desaverbacao_de_Periodos_Como_isso_pode_te_AJUDAR_ou_ATRAPALHAR": "https://youtu.be/SweEgpH29W4",
  "YT-2024-07-09-Serie_CTC_e_RPPS_-_Periodo_Trabalhado_na_Prefeitura_e_Nao_Reconhecido_-_Entenda_os_Absurdos_do_Direito": "https://youtu.be/IVJK_K2_7pM",
  "YT-2024-07-12-Institucional_Pellizzetti_e_Walber_e_Associados_-_A_historia_por_tras_do_processo": "https://youtu.be/EpI5KziF548",
  "YT-2024-07-16-ERRO_da_Justica_-_Aposentadoria_Sem_Carencia_Apos_Mudanca_de_SEXO": "https://youtu.be/tz7yBUhTpAs",
  "YT-2024-07-18-Entenda_como_funciona_APOSENTADORIA_ESPECIAL_do_SERVIDOR_PUBLICO": "https://youtu.be/z5oEpeZw3XY",
  "YT-2024-07-24-Vale_a_Pena_Indenizar_o_Tempo_Rural_para_Aposentadoria_no_RPPS": "https://youtu.be/b1yM0HW-Fyw",
  "YT-2024-07-25-Vale_a_Pena_Indenizar_o_Tempo_Rural_para_Aposentadoria_no_INSS": "https://youtu.be/hW_Xm1Ty8OM",
  "YT-2024-08-08-WhatsAppOrganizer_criando_uma_ferramenta_para_ajudar_os_advogados": "https://youtu.be/X_JlLlebbx0",
  "YT-2024-08-09-Pontos_Controvertidos_ou_nao_e_Recontrovertidos_pelo_Magistrado": "https://youtu.be/nTJbqo0saU4",
  "YT-2024-08-13-Aposentadoria_Especial_sobre_niveis_de_RUIDOS_-_Parte_1_de_3": "https://youtu.be/pSTPjFqPcu8",
  "YT-2024-08-15-Posso_receber_AUXILIO-ACIDENTE_e_DOENCA_ao_mesmo_tempo": "https://youtu.be/2dbxeg09Mtw",
  "YT-2024-08-20-Tinha_tempo_Especial_e_nao_utilizei_na_minha_aposentadoria_-_E_agora": "https://youtu.be/nQbAxvxb2Gc",
  "YT-2024-08-22-EPI_contra_ruido_garante_APOSENTADORIA_ESPECIAL_Entenda_as_novas_regras_do_INSS_em_2024_-_Parte_2": "https://youtu.be/wcPCsvim058",
  "YT-2024-08-27-Entenda_o_PERIODO_DE_GRACA_no_INSS_-_Seus_direitos_e_como_manter_a_qualidade_de_segurado": "https://youtu.be/2KnfW51A0Pw",
  "YT-2024-08-29-Entendendo_a_AVALIACAO_DE_RUIDOS_na_Aposentadoria_Especial_-_Parte_3": "https://youtu.be/WjTpiOHRSF0",
  "YT-2024-09-11-Sumula_111_do_STJ_Confirmada_-_Mais_uma_decisao_que_prejudica_os_advogados_e_segurados": "https://youtu.be/PVHpBFaQrcc",
  "YT-2024-09-24-Compra_e_Venda_de_Precatorios_Previdenciarios_E_outros_vale_a_pena": "https://youtu.be/I93QydTxh98",
  "YT-2024-09-24-Novidades_na_Aposentadoria_Complementar_do_Servidor_Publico_Paranaense_-_RPPS_Regime_Proprio": "https://youtu.be/sEh9Vwuu3kQ",
  "YT-2024-09-25-Projudi_Crawler_-_Adicionando_Redundancia_nos_Sistemas_Judiciais": "https://youtu.be/xshuGZvngsc",
  "YT-2024-09-26-Fim_e_Retorno_do_Minimo_Divisor_nas_Aposentadorias_do_INSS": "https://youtu.be/znGUL7aXTCE",
  "YT-2024-10-01-Tema_1018_do_STJ_-_O_favoritos_dos_advogados_e_como_conseguir_os_dois_melhores_beneficios_do_INSS": "https://youtu.be/dYuWSdjhO2I",
  "YT-2024-10-03-Pensao_por_Morte_-_Como_garantir_100%_do_Beneficio_Conceitos_que_podem_mudar_seu_beneficio": "https://youtu.be/bLVpQGEpqmI",
  "YT-2024-10-08-Injusto_entendimento_sobre_o_Militar_PM_que_migra_para_o_INSS_esta_sendo_alterado": "https://youtu.be/w45-fUpPqXY",
  "YT-2024-10-10-Pensao_por_Morte_Rural_e_um_pagamento_que_levou_ao_indeferimento_do_beneficio": "https://youtu.be/beWLWILqQBU",
  "YT-2024-10-15-Como_conseguir_e_discutir_a_validade_de_PPP_e_LTCAT_para_aposentadoria_especial_no_RPPS": "https://youtu.be/e9fvnfJcsD8",
  "YT-2024-10-17-ALERTA_Cuidado_ao_requerer_sua_pensao_por_morte_-_Extincao_nao_reversivel_das_cotas_apos_a_idade": "https://youtu.be/VZ5mDnkOUlQ",
  "YT-2024-10-22-Desvio_de_funcao_no_RPPS_-_Quais_sao_as_consequencias": "https://youtu.be/v2YEm375Qn4",
  "YT-2024-10-24-Pensao_por_Morte_e_Novo_casamento_no_INSS_e_no_RPPS_PR_-_Confira_suas_regras_para_nao_ter_surpresa": "https://youtu.be/xDGxp979ENI",
  "YT-2024-10-25-Tutorial_de_IA_-_Como_facilitar_seu_Dia-Dia_com_essa_Ferramenta_-_Introducao": "https://youtu.be/Uw8ONSyaHBk",
  "YT-2024-10-29-Recolhimento_em_Atraso_do_Socio_Quotista_-_Um_caso_unico_ou_uma_realidade": "https://youtu.be/56mDR1hCGWY",
  "YT-2024-10-31-Tutorial_-_Como_pedir_seu_auxilio_doenca_em_2024_Atualizado_Pelo_MEU_INSS_de_forma_gratuita_e_online": "https://youtu.be/JQLdW99WTJA",
  "YT-2024-11-01-Tutorial_de_IA_-_Conceitos_basicos_e_como_superar_os_desafios_do_futuro": "https://youtu.be/bXV_TNcuDG4",
  "YT-2024-11-05-4_MENTIRAS_do_INSS_sobre_os_beneficios_previdenciarios": "https://youtu.be/A0qqlzUOD84",
  "YT-2024-11-12-CTC_-_Certidao_de_Tempo_de_Contribuicao_no_RPPS_para_fins_DECLARATORIOS_-_Cuidado_com_as_averbacoes": "https://youtu.be/XRC0AFq9hqg",
  "YT-2024-11-14-Tutorial_-_Como_fazer_cumprimento_de_EXIGENCIA_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/WXS6OUFYrcE",
  "YT-2024-11-19-Noticia_Importante_RPPS_-_TCE_MG_admite_recebimento_de_Abono_de_Permanencia_e_o_Melhor_Beneficio": "https://youtu.be/sQXC8dvg2vc",
  "YT-2024-11-21-4_Armadilhas_Previdenciarias_do_INSS_-_Fique_atento_aos_seus_direitos_para_nao_ter_surpresas_futuras": "https://youtu.be/8_58EtyioiQ",
  "YT-2024-11-26-Como_funciona_a_Justica_Federal_Previdenciaria_e_como_isso_afeta_o_seu_pedido_de_aposentadoria": "https://youtu.be/2G2QwmWnm90",
  "YT-2024-11-28-Boas_Noticias_-_Fim_da_Discussao_Sobre_o_Imposto_de_Renda_Fixo_em_25%_Brasileiro_no_Exterior": "https://youtu.be/Z5LCqISc158",
  "YT-2024-12-03-Noticia_-_Albino_Indigena_recebe_BPC_-_Entendendo_mais_sobre_beneficios_previdenciarios_e_incapacidade": "https://youtu.be/6IGGrAmpyIw",
  "YT-2024-12-05-Tutorial_-_Per_DCOMP_Recolhimento_Incorreto_Servidor_Publico": "https://youtu.be/TuyO_jl6i9s",
  "YT-2024-12-10-Tutorial_-_Como_entrar_com_processo_sem_ADVOGADO_-_JUS_POSTULANDI": "https://youtu.be/wVaj5cderCQ",
  "YT-2024-12-12-Tutorial_-_Como_acessar_PPP_digital_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/ku5SgQRhQC8",
  "YT-2025-01-07-Como_o_BENZENO_afeta_sua_saude_e_a_sua_aposentadoria_-_entenda_um_pouco_mais_sobre_este_elemento": "https://youtu.be/yDMxkGEEoUA",
  "YT-2025-01-09-Exposicao_a_agentes_Biologicos_e_Profissoes_Incomuns_-_entendendo_mais_sobre_aposentadoria_Especial": "https://youtu.be/5R6-uOPTFnY",
  "YT-2025-01-14-Aposentadoria_Especial_do_Tecnico_de_Protese_Dentaria": "https://youtu.be/IY7l0KBnlRY",
  "YT-2025-01-16-Conflitos_de_Deficiencias_-_qual_e_o_criterio_definitivo_para_a_Lei_e_para_a_Justica": "https://youtu.be/VMaxtbBtoNs",
  "YT-2025-01-21-Isencao_de_Imposto_de_Renda_e_Doencas_Graves_em_2025": "https://youtu.be/AjLiAGgE3j8",
  "YT-2025-01-23-Maior_Erro_do_Advogado_Previdenciario_-_Confiar_na_Contagem_Processual": "https://youtu.be/CnghGbX50r0",
  "YT-2025-01-28-Isencao_Contribuicao_Previdenciaria_por_Doenca_Grave_-_um_Direito_Extinto_-_RPPS_PR": "https://youtu.be/nGwPsZheBXM",
  "YT-2025-01-29-Tutorial_de_IA_-_Entenda_o_que_e_um_modelo_e_como_a_inteligencia_da_IA_funciona": "https://youtu.be/27FeN1aVEvI",
  "YT-2025-01-30-como_fazer_REAJUSTE_das_contribuicoes_do_INSS_-_De_forma_ONLINE_e_SIMPLES": "https://youtu.be/RN77EsX_804",
  "YT-2025-02-05-Tutorial_de_IA_-_Como_navegar_no_mundo_da_IA_sem_se_perder_em_milhares_de_APLICATIVOS": "https://youtu.be/mF6SmRiy70c",
  "YT-2025-02-06-Jovem_Advogado_-_Nunca_perda_o_sentimento_de_Justica_que_temos_no_primeiro_ano_da_faculdade": "https://youtu.be/ejfUXfv-VwY",
  "YT-2025-02-11-Revisao_da_Vida_Toda_-_Cortes_e_Comentarios": "https://youtu.be/Z87X6lY2iWQ",
  "YT-2025-02-12-Tutorial_de_IA_-_Como_API_Frontend_e_Backend_Funcionam_nos_Aplicativos_Modernos": "https://youtu.be/Xezxp4H399A",
  "YT-2025-02-13-Aposentadoria_e_Ultimo_Salario_-_O_que_voce_precisa_saber": "https://youtu.be/sItQyAC91Q0",
  "YT-2025-02-18-Previdencia_e_aposentadoria_mudancas_do_INSS_em_2024_e_2025": "https://youtu.be/aP10ZoSJ110",
  "YT-2025-02-19-Tutorial_de_IA_-_O_que_e_uma_API_KEY_E_como_conseguir_sua_API_KEY_da_OpenAI_e_Claude": "https://youtu.be/twlxL4wbnc8",
  "YT-2025-02-20-Beneficios_do_INSS_alem_da_Aposentadoria_e_Pensao_por_Morte_Voce_conhece_todos": "https://youtu.be/9CPdTp-hO_Q",
  "YT-2025-02-25-Como_evitar_erros_ao_pagar_o_INSS_No_comeco_do_ano_e_nao_prejudicar_sua_aposentadoria": "https://youtu.be/EC-XmMEVmsk",
  "YT-2025-02-26-Tutorial_de_IA_-_Os_principais_Players_do_mercado_da_Inteligencia_Artificial": "https://youtu.be/Q0FR5dSVfGk",
  "YT-2025-02-27-INSS_2025_-_Por_que_voce_NAO_vai_se_aposentar_pelo_teto_Uma_regra_de_calculo_inflacionario": "https://youtu.be/pLUFgq4rwSI",
  "YT-2025-03-05-Tutorial_de_IA_-_Assistentes_Agentes_IA_podem_otimizar_suas_tarefas": "https://youtu.be/LckiKu41eDw",
  "YT-2025-03-11-Tutorial_-_Como_pedir_seu_auxilio_doenca_em_2025_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "https://youtu.be/TA3FA7C2970",
  "YT-2025-03-12-Tutorial_de_IA_-_A_IA_tem_MEMORIA_Como_as_THREADS_ajudam_a_manter_o_contexto_das_respostas": "https://youtu.be/Ec5467zbtAw",
  "YT-2025-03-13-Tutorial_-_Pedir_Aposentadoria_por_IDADE_em_2025_e_FACIL_com_o_MEU_INSS": "https://youtu.be/vqv2N8gbURY",
  "YT-2025-03-17-Prev_IA_-_O_Robo_Previdenciario_do_Parana_e_Realmente_Inteligente": "https://youtu.be/ysVYRkxsm30",
  "YT-2025-03-18-Aposentadoria_Especial_-_Como_comprovar_a_exposicao_a_vibracao": "https://youtu.be/P0IN2wM32T8",
  "YT-2025-03-19-Tutorial_de_IA_-_O_que_e_Fine_Tuning_e_como_ele_melhora_sua_IA": "https://youtu.be/jWSTzH7jDwc",
  "YT-2025-03-20-Tutorial_-_Pesquisa_de_Jurisprudencia_para_Advogados_-_Como_agilizar_e_refinar_seus_resultados": "https://youtu.be/YCEEAsjkuuE",
  "YT-2025-03-25-Aposentadoria_Especial_-_Como_a_ineficacia_do_EPI_garantiu_a_VITORIA_neste_Caso": "https://youtu.be/t5S2CcudIAM",
};

// Titulos oficiais para referencia
export const YT_TITLES = {
  "YT-2018-08-10-Tutorial_-_Como_pesquisar_Jurisprudencia_Previdenciaria_no_TRF4": "Tutorial - Como pesquisar Jurisprudência Previdenciária no TRF4",
  "YT-2020-12-08-Bruno_Responde_-_Como_funciona_a_aposentadoria_do_deficiente": "Bruno Responde: Como funciona a aposentadoria do deficiente?",
  "YT-2021-02-02-A_importancia_do_recolhimento_previdenciario_para_o_beneficiario_do_LOAS_BPC_que_tem_dependentes": "A importância do recolhimento previdenciário para o beneficiário do LOAS/BPC que tem dependentes",
  "YT-2021-02-12-Aposentadoria_especial_do_servidor_publico_da_saude_-_Regime_proprio_IPMC_e_outros": "Aposentadoria especial do servidor público da saúde: Regime próprio, IPMC e outros",
  "YT-2021-02-18-Por_que_todos_devem_contribuir_com_o_INSS": "Por que todos devem contribuir com o INSS?",
  "YT-2021-02-25-Regra_do_Descarte_aposentadoria_apos_Reforma_da_Previdencia_EC_103_2019": "Regra do Descarte aposentadoria após Reforma da Previdência EC 103/2019",
  "YT-2021-02-26-TESE_DO_DESCARTE_MAXIMO_-_O_maior_furo_do_INSS_dos_ultimos_tempos": "TESE DO DESCARTE MÁXIMO: O maior furo do INSS dos últimos tempos!!!",
  "YT-2021-03-09-15_dicas_sobre_o_Auxilio-acidente": "15 dicas sobre o Auxílio-acidente",
  "YT-2021-03-11-Revisao_do_LOAS_BPC_-_Convertendo_em_aposentadoria_por_invalidez": "Revisão do LOAS/BPC: Convertendo em aposentadoria por invalidez",
  "YT-2021-03-18-Aposentadoria_do_Professor_no_RPPS": "Aposentadoria do Professor no RPPS",
  "YT-2021-03-23-Aposentadoria_Especial_pos_Reforma_da_Previdencia": "Aposentadoria Especial pós Reforma da Previdência",
  "YT-2021-03-25-E_possivel_acumular_a_pensao_por_morte_com_minha_aposentadoria": "É possível acumular a pensão por morte com minha aposentadoria?",
  "YT-2021-04-06-CASO_PRATICO_-_aposentadoria_do_Professor_servidor_publico": "CASO PRÁTICO: aposentadoria do Professor servidor público",
  "YT-2021-04-16-15_dicas_sobre_pensao_por_morte": "15 dicas sobre pensão por morte",
  "YT-2021-04-20-Aposentadoria_-_180_contribuicoes_ou_15_anos": "Aposentadoria: 180 contribuições ou 15 anos?",
  "YT-2021-04-27-Passo_a_passo_do_requerimento_de_pensao_por_morte": "Passo a passo do requerimento de pensão por morte",
  "YT-2021-05-07-Saiba_tudo_sobre_a_Lei_de_indenizacao_para_vitimas_do_enfrentamento_da_COVID-19": "Saiba tudo sobre a Lei de indenização para vítimas do enfrentamento da COVID-19",
  "YT-2021-05-11-Agencia_do_INSS_fechada_Conheca_as_novas_regras_da_Portaria_Conjunta_32_de_31_de_Marco_de_2021": "Agência do INSS fechada? Conheça as novas regras da Portaria Conjunta 32 de 31 de Março de 2021",
  "YT-2021-05-20-Manual_da_Aposentadoria_por_Idade_Urbana_-_INSS": "Manual da Aposentadoria por Idade Urbana - INSS",
  "YT-2021-05-27-LOAS_BPC_-_5_dicas_para_evitar_o_pente_fino_do_INSS": "LOAS/BPC: 5 dicas para evitar o pente fino do INSS",
  "YT-2021-06-01-FAKE_NEWS_-_Visao_monocular_e_o_direito_a_aposentadoria_por_invalidez": "FAKE NEWS: Visão monocular e o direito à aposentadoria por invalidez",
  "YT-2021-06-11-Entrevista_com_o_cliente_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "Entrevista com o cliente - Série Requerimentos Previdenciários de A a Z",
  "YT-2021-06-15-Pensao_por_morte_para_o_homem_a_partir_da_Constituicao_Federal_de_1988_-_VITORIA_E_IGUALDADE": "Pensão por morte para o homem a partir da Constituição Federal de 1988: VITÓRIA E IGUALDADE",
  "YT-2021-06-24-O_que_fazer_quando_o_INSS_demora_para_analisar_um_beneficio": "O que fazer quando o INSS demora para analisar um benefício?",
  "YT-2021-07-15-Analise_e_conferencia_CNIS_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "Análise e conferência CNIS - Série Requerimentos Previdenciários de A a Z",
  "YT-2021-07-20-Os_direitos_previdenciarios_do_Autista_TEA": "Os direitos previdenciários do Autista (TEA)",
  "YT-2021-07-27-Estou_gravida._Tenho_direito_ao_salario-maternidade": "Estou grávida. Tenho direito ao salário-maternidade?",
  "YT-2021-08-03-Como_funciona_a_regra_dos_pontos_do_INSS": "Como funciona a regra dos pontos do INSS?",
  "YT-2021-08-13-Tudo_o_que_voce_precisa_saber_sobre_Salario_Maternidade": "Tudo o que você precisa saber sobre Salário Maternidade",
  "YT-2021-08-17-Aposentadoria_do_servidor_publico_-_agente_penitenciario_DEPEN": "Aposentadoria do servidor público: agente penitenciário DEPEN",
  "YT-2021-08-24-5_dicas_para_evitar_fraudes_contra_aposentados_e_pensionistas": "5 dicas para evitar fraudes contra aposentados e pensionistas",
  "YT-2021-09-02-Pensao_por_morte_e_irretroatividade": "Pensão por morte e irretroatividade",
  "YT-2021-09-08-A_acao_mais_dificil_do_direito_previdenciario": "A ação mais difícil do direito previdenciário",
  "YT-2021-09-14-Busca_de_documentos_comprobatorios_-_Serie_Requerimentos_Previdenciarios_de_A_a_Z": "Busca de documentos comprobatórios - Série Requerimentos Previdenciários de A a Z",
  "YT-2021-09-22-Posso_acumular_mais_de_um_beneficio_do_INSS": "Posso acumular mais de um benefício do INSS?",
  "YT-2021-09-28-Sou_MEI_microempreendedor_individual_posso_me_aposentar": "Sou MEI (microempreendedor individual), posso me aposentar?",
  "YT-2021-10-28-Como_complementar_as_contribuicoes_previdenciarias_do_MEI_e_baixa_renda_para_Aposentadoria": "Como complementar as contribuições previdenciárias do MEI e baixa renda para Aposentadoria",
  "YT-2021-11-24-Servidor_publico_pode_ter_empresa": "Servidor público pode ter empresa?",
  "YT-2021-11-30-A_inconstitucionalidade_da_NOVA_Pensao_por_Morte": "A inconstitucionalidade da NOVA Pensão por Morte",
  "YT-2023-01-12-Mudancas_no_auxilio_reclusao": "Mudanças no auxílio reclusão",
  "YT-2023-01-14-Aprenda_a_criar_uma_conta_Gov.br_de_forma_rapida_e_facil": "Aprenda a criar uma conta Gov.br, de forma rápida e fácil",
  "YT-2023-01-15-Tutorial_de_como_acessar_os_dados_do_CNIS_e_qual_sua_utilidade": "Tutorial de como acessar os dados do CNIS, e qual sua utilidade!!",
  "YT-2023-01-17-Tutorial_-_Como_acessar_a_Revisao_da_Vida_Toda_-_Carta_de_Concessao_pelo_portal_Meu.INSS": "Tutorial: Como acessar a Revisão da Vida Toda - Carta de Concessão, pelo portal Meu.INSS",
  "YT-2023-01-18-Tutorial_-_Requerimento_do_Auxilio-Doenca_em_2023_de_forma_gratuita_online_e_rapida": "Tutorial: Requerimento do Auxílio-Doença em 2023, de forma gratuíta, online e rápida",
  "YT-2023-02-10-Como_recolher_contribuicao_em_atraso_sendo_ADVOGADO": "Como recolher contribuição em atraso, sendo ADVOGADO",
  "YT-2023-02-28-Analise_do_caso_pratico_de_Aposentadoria_por_Idade_com_tempo_de_servico_miitar._PARTE_1.": "Análise do caso prático de Aposentadoria por Idade, com tempo de serviço miitar. PARTE 1.",
  "YT-2023-03-28-Como_ajustar_o_codigo_de_recolhimento_do_INSS_ajuste_de_guias_erro_de_recolhimento": "Como ajustar o código de recolhimento do INSS ajuste de guias erro de recolhimento",
  "YT-2023-05-17-Escritorio_de_Advocacia_e_advogado_-_Passo_a_passo_do_simples_Nacional_-_parte_1_-_Pedido_inicial": "Escritório de Advocacia e advogado: Passo a passo do simples Nacional - parte 1: Pedido inicial",
  "YT-2023-05-19-Aposentadoria_e_Auxilio_Doenca_para_portador_de_HIV_-_Doencas_Estigmatizantes": "Aposentadoria e Auxílio Doença para portador de HIV - Doenças Estigmatizantes",
  "YT-2023-05-23-Escritorio_de_Advocacia_e_advogado_-_Passo_a_passo_do_simples_Nacional_-_parte_2_-_Apos_Deferimento": "Escritório de Advocacia e advogado: Passo a passo do simples Nacional - parte 2: Após Deferimento",
  "YT-2023-05-30-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P3_Preenchimento_Empresa_Facil": "Escritório Advocacia e advogado: Passo a passo do Simples Nacional - P3 Preenchimento Empresa Fácil",
  "YT-2023-06-02-Tutorial_-_Requerimento_da_Aposentadoria_por_Idade_em_2023_de_forma_gratuita_online_e_rapida": "Tutorial: Requerimento da Aposentadoria por Idade em 2023, de forma gratuíta, online e rápida",
  "YT-2023-06-06-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P4_Contrato_Social": "Escritório Advocacia e advogado: Passo a passo do Simples Nacional - P4 Contrato Social",
  "YT-2023-06-08-Aposentadoria_e_Auxilio_Doenca_para_quem_tem_Bipolaridade_-_Doencas_Estigmatizantes": "Aposentadoria e Auxílio Doença para quem tem Bipolaridade - Doenças Estigmatizantes",
  "YT-2023-06-13-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_P5_Conferencia_Final_e_Documentos": "Escritório Advocacia e advogado: Passo a passo do Simples Nacional P5 Conferência Final e Documentos",
  "YT-2023-06-15-Aposentadoria_Especial_-_Para_Dono_de_Posto_de_Combustiveis": "Aposentadoria Especial:  Para Dono de Posto de Combustíveis",
  "YT-2023-06-20-Escritorio_Advocacia_e_advogado_-_Passo_a_passo_do_Simples_Nacional_-_P6_-_Opcao_Pelo_Simples": "Escritório Advocacia e advogado: Passo a passo do Simples Nacional - P6 - Opção Pelo Simples",
  "YT-2023-06-22-Pensao_por_Morte_Rural_em_2023_-_Como_solicitar_de_forma_rapida_e_gratuita.": "Pensão por Morte Rural em 2023: Como solicitar de forma rápida e gratuita.",
  "YT-2023-06-27-Pensao_por_morte_para_filho_nao_nascido_-_O_que_voce_precisa_saber": "Pensão por morte para filho não nascido - O que você precisa saber",
  "YT-2023-06-29-Decisao_Injusta_-_Impactos_da_Sumula_111_no_Direito_Previdenciario": "Decisão Injusta: Impactos da Súmula 111 no Direito Previdenciário",
  "YT-2023-07-04-Aposentadoria_Especial_em_Postos_de_Combustivel_-_Decisao_Importante_do_INSS": "Aposentadoria Especial em Postos de Combustível: Decisão Importante do INSS!",
  "YT-2023-07-04-Aposentadoria_e_Auxilio_Doenca_para_portador_de_Cancer_de_Pele._Doencas_Estigmatizantes": "Aposentadoria e Auxílio Doença para portador de Câncer de Pele. Doenças Estigmatizantes",
  "YT-2023-07-11-Acesso_aos_Laudos_Medicos_-_Descubra_o_Motivo_do_Indeferimento_em_2023": "Acesso aos Laudos Médicos: Descubra o Motivo do Indeferimento em 2023!",
  "YT-2023-07-13-Problemas_com_a_Simulacao_do_Meu_INSS_-_Caso_Real": "Problemas com a Simulação do Meu INSS - Caso Real",
  "YT-2023-07-18-Tripla_Acumulacao_de_Beneficio_-_O_Polemico_Debate_que_Afeta_Pensionistas": "Tripla Acumulação de Benefício: O Polêmico Debate que Afeta Pensionistas",
  "YT-2023-08-01-Aposentadoria_e_Auxilio_Doenca_para_portador_de_Esquizofrenia._Doencas_Estigmatizantes": "Aposentadoria e Auxílio Doença para portador de Esquizofrenia. Doenças Estigmatizantes",
  "YT-2023-08-03-Tutorial_-_Como_Elaborar_uma_Peticao_Inicial_de_Incapacidade_em_2023": "Tutorial: Como Elaborar uma Petição Inicial de Incapacidade em 2023",
  "YT-2023-08-22-Novidades_no_Tema_1019_do_STF_-_Vitoria_pela_Integralidade_dos_Policiais_Civis_-_RPPS": "Novidades no Tema 1019 do STF - Vitória pela Integralidade dos Policiais Civis - RPPS",
  "YT-2023-08-25-Tutorial_Como_Regularizar_Contribuicoes_Abaixo_do_Minimo_Legal": "Tutorial Como Regularizar Contribuições Abaixo do Mínimo Legal",
  "YT-2023-08-29-As_5_grandes_mentiras_sobre_Aposentadoria_do_INSS": "As 5 grandes mentiras sobre Aposentadoria do INSS",
  "YT-2023-08-31-Valor_da_Aposentadoria_por_Invalidez_menor_Auxilio_Doenca_do_INSS._Entenda_essa_regra_prejudicial": "Valor da Aposentadoria por Invalidez menor Auxílio Doença do INSS. Entenda essa regra prejudicial!",
  "YT-2023-09-05-Aposentadoria_Especial_do_Coveiro_-_Caso_Real_-_Vitoria_do_Caso._RPPS": "Aposentadoria Especial do Coveiro: Caso Real - Vitoria do Caso. RPPS",
  "YT-2023-09-12-O_Que_NAO_Fazer_na_SUA_Pericia_Medica_do_INSS_5_Dicas_para_Conseguir_sua_Aprovacao": "O Que NÃO Fazer na SUA Perícia Médica do INSS? 5 Dicas para Conseguir sua Aprovação!",
  "YT-2023-09-14-4_ERROS_que_Podem_Atrapalhar_sua_Aposentadoria_-_Descubra_o_que_o_INSS_nao_te_contou": "4 ERROS que Podem Atrapalhar sua Aposentadoria: Descubra o que o INSS não te contou!",
  "YT-2023-09-19-Desvendando_a_Nova_Aposentadoria_-_3_Regras_de_Transicao_que_VOCE_Precisa_Conhecer_no_INSS": "Desvendando a Nova Aposentadoria: 3 Regras de Transição que VOCÊ Precisa Conhecer no INSS",
  "YT-2023-09-26-Como_pedir_sua_Aposentadoria_por_Idade_em_2023_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Como pedir sua Aposentadoria por Idade em 2023 pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2023-09-29-Aposentadoria_Especial_do_Eletricista_-_Aprenda_como_ler_e_corrigir_o_PPP_igual_ao_INSS_e_a_Justica": "Aposentadoria Especial do Eletricista: Aprenda como ler e corrigir o PPP igual ao INSS e a Justiça",
  "YT-2023-10-03-Aposentadoria_Especial_do_Pedreiro_Como_Conseguir_a_Aposentadoria_e_Melhorar_seu_Valor": "Aposentadoria Especial do Pedreiro Como Conseguir a Aposentadoria e Melhorar seu Valor",
  "YT-2023-10-10-Aposentado_e_Pensionista_no_Exterior_Desconto_de_25%_FIXO_Para_Quem_Mora_no_Exterior_Tema_1174_STF": "Aposentado e Pensionista no Exterior Desconto de 25% FIXO Para Quem Mora no Exterior Tema 1174 STF",
  "YT-2023-10-19-Lei_259_de_2023_PR_Nova_Carreira_Escrivao_e_Agente_Policia_Civil_O_que_fazer_Servidor_e_Aposentado": "Lei 259 de 2023 PR Nova Carreira Escrivão e Agente Policia Civil O que fazer? Servidor e Aposentado",
  "YT-2023-10-24-Decisao_TCE_PR_pode_salvar_aposentadoria_e_abono_servidor_publico_PRPREV_LC_233_21_e_EC_45_2019": "Decisão TCE PR pode salvar aposentadoria e abono servidor público PRPREV LC 233/21 e EC 45/2019",
  "YT-2023-10-26-Um_erro_do_INSS_que_poderia_ter_custado_caro_para_uma_empregada_publica_da_CEF": "Um erro do INSS que poderia ter custado caro para uma empregada pública da CEF",
  "YT-2023-11-01-Duplo_Pedagio_para_Aposentadoria_Integralidade_e_Paridade_do_Policial_e_Seguranca_Publica_Parana": "Duplo Pedágio para Aposentadoria Integralidade e Paridade do Policial e Segurança Pública Paraná",
  "YT-2023-11-14-Entenda_tudo_sobre_revisao_de_Aposentadoria_e_Pensao_no_RPPS": "Entenda tudo sobre revisão de Aposentadoria e Pensão no RPPS",
  "YT-2023-11-17-Tutorial_ePROTOCOLO_Parana_-_Como_Cadastrar_Cadastro_Inicial_parana": "Tutorial ePROTOCOLO Paraná - Como Cadastrar? Cadastro Inicial #paraná",
  "YT-2023-11-22-Tutorial_ePROTOCOLO_Parte_2_-_Como_fazer_um_requerimento_simples_Por_exemplo_CTC": "Tutorial ePROTOCOLO Parte 2 : Como fazer um requerimento simples? Por exemplo CTC",
  "YT-2023-11-24-Servidor_Publico_pode_abrir_MEI_Confira_esse_e_outros_questionamentos_do_RPPS_relacionado_ao_INSS": "Servidor Público pode abrir MEI? Confira esse e outros questionamentos do RPPS relacionado ao INSS",
  "YT-2023-12-01-Entenda_a_restricao_da_Triplice_Acumulacao_de_Beneficios_e_cargos_servidores_publicos_no_TCU_RPPS": "Entenda a restrição da Tríplice Acumulação de Benefícios e cargos servidores públicos no TCU #RPPS",
  "YT-2023-12-04-Previdencia_Complementar_Parana_-_Como_vai_funcionar_a_aposentadoria_para_os_novos_servidores": "Previdência Complementar Paraná: Como vai funcionar a aposentadoria para os novos servidores",
  "YT-2023-12-12-Auxilio_Acidente_no_MEI_-_Um_beneficio_que_tem_sido_esquecido": "Auxílio Acidente no MEI - Um benefício que tem sido esquecido",
  "YT-2024-02-15-Revisao_da_Aposentadoria_e_Pensao_no_Teto_Maximo_e_Teto_Minimo_Atualmente_direitoprevidenciario": "Revisão da Aposentadoria e Pensão no Teto Máximo e Teto Mínimo Atualmente #direitoprevidenciário",
  "YT-2024-02-27-Aposentadoria_especial_do_FRENTISTA_e_do_CAIXA_postodecombustivel": "Aposentadoria especial do FRENTISTA e do CAIXA #postodecombustivel",
  "YT-2024-02-29-Pedido_de_Aposentadoria_Especial_negado_com_muitos_erros_aprenda_como_corrigir_com_essa_estrategia": "Pedido de Aposentadoria Especial negado com muitos erros, aprenda como corrigir com essa estratégia",
  "YT-2024-03-01-Entrevista_com_o_Dr.Calc_Eduardo_Teixeira_Maggi": "Entrevista com o Dr.Calc Eduardo Teixeira Maggi",
  "YT-2024-03-01-Trailer_do_Canal": "Trailer do Canal",
  "YT-2024-03-08-Como_pedir_seu_auxilio_doenca_em_2024_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Como pedir seu auxílio doença em 2024 pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2024-03-08-Como_pedir_sua_Aposentadoria_por_Idade_em_2024_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Como pedir sua Aposentadoria por Idade em 2024 pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2024-03-12-Aposentadoria_Negada_Indeferida_-_Enfermeiras_e_Auxiliar_de_Enfermagem_-_O_que_fazer": "Aposentadoria Negada/Indeferida: Enfermeiras e Auxiliar de Enfermagem - O que fazer?",
  "YT-2024-04-03-Aposentadoria_Especial_do_MOTORISTA_-_Uma_batalha_perdida": "Aposentadoria Especial do MOTORISTA - Uma batalha perdida?",
  "YT-2024-04-03-Como_pedir_DESISTENCIA_de_Beneficio_em_2024_pelo_MEU_INSS": "Como pedir DESISTÊNCIA de Benefício em 2024 pelo MEU INSS",
  "YT-2024-04-23-Aposentei_pelo_INSS_SEM_averbar_o_tempo_rural_e_agora_Revisao_do_Tempo_Rural": "Aposentei pelo INSS SEM averbar o tempo rural, e agora? Revisão do Tempo Rural",
  "YT-2024-05-07-Posso_pagar_o_INSS_em_atraso_para_me_aposentar": "Posso pagar o INSS em atraso para me aposentar?",
  "YT-2024-05-09-Aposentadoria_do_Deficiente_Apos_a_Reforma_da_Previdencia_EC_103_2019_Entenda_a_Disputa_dos_80x100": "Aposentadoria do Deficiente Após a Reforma da Previdência (EC 103/2019) Entenda a Disputa dos 80x100",
  "YT-2024-05-13-Visao_Monocular_-_Uma_Rediscussao_EQUIVOCADA_da_Lei_Amalia_Barros_-_LEI_14.126_de_2021": "Visão Monocular - Uma Rediscussão EQUÍVOCADA da Lei Amália Barros: LEI 14.126 de 2021",
  "YT-2024-05-15-Aposentadoria_do_Trabalhador_Rural_em_2024_-_Guia_Completo_do_Segurado_Especial_-_O_que_nao_fazer": "Aposentadoria do Trabalhador Rural em 2024 - Guia Completo do Segurado Especial - O que não fazer!",
  "YT-2024-05-21-Como_analisar_sua_carta_de_CONCESSAO_do_meu_INSS_de_forma_simples_e_rapida": "Como analisar sua carta de CONCESSÃO do meu INSS, de forma simples e rápida",
  "YT-2024-05-23-Aposentadoria_Especial_do_Vigilante_-_Mais_um_Direito_Na_Mira_do_STF_-_Tema_1209": "Aposentadoria Especial do Vigilante - Mais um Direito Na Mira do STF: Tema 1209",
  "YT-2024-06-06-Como_criei_um_Robo_para_responder_perguntas_diarias_usando_Llamaindex_+_WhatsApp_+_ChatGPT": "Como criei um Robô para responder perguntas diárias usando Llamaindex + WhatsApp + ChatGPT",
  "YT-2024-06-17-Como_funciona_a_APOSENTADORIA_da_pessoa_com_Deficiencia_no_RPPS": "Como funciona a APOSENTADORIA da pessoa com Deficiência no RPPS",
  "YT-2024-06-18-Tema_810_STF_-_A_Vitoria_do_IPCA_e_a_AINDA_possivel_revisao_de_Previdenciarios_e_Precatorios_INSS": "Tema 810 STF: A Vitória do IPCA e a AINDA possível revisão de Previdenciários e Precatórios (INSS)",
  "YT-2024-06-20-O_que_acontece_quando_mudo_meu_regime_previdenciario_como_servidor_publico_Entenda_migracao_de_CTC": "O que acontece quando mudo meu regime previdenciário como servidor público? Entenda migração de CTC",
  "YT-2024-06-25-Advogado_-_Entenda_como_conseguir_a_Ajuda_do_Juiz_para_resolver_questoes_dificeis_nos_seus_processos": "Advogado: Entenda como conseguir a Ajuda do Juiz para resolver questões difíceis nos seus processos",
  "YT-2024-06-27-Serie_CTC_e_RPPS_-_O_que_nao_fazer_quando_voce_esta_proximo_de_se_aposentar_no_Regime_Publico": "Série CTC e RPPS: O que não fazer quando você está próximo de se aposentar no Regime Público",
  "YT-2024-07-02-Serie_CTC_e_RPPS_-_O_servidor_pode_recolher_sua_contribuicao_em_atraso_-_Entenda_esse_caso_na_licenca": "Série CTC e RPPS: O servidor pode recolher sua contribuição em atraso - Entenda esse caso na licença",
  "YT-2024-07-04-Serie_CTC_e_RPPS_-_Averbacao_e_Desaverbacao_de_Periodos_Como_isso_pode_te_AJUDAR_ou_ATRAPALHAR": "Série CTC e RPPS: Averbação e Desaverbação de Períodos Como isso pode te AJUDAR ou ATRAPALHAR?",
  "YT-2024-07-09-Serie_CTC_e_RPPS_-_Periodo_Trabalhado_na_Prefeitura_e_Nao_Reconhecido_-_Entenda_os_Absurdos_do_Direito": "Série CTC e RPPS: Período Trabalhado na Prefeitura e Não Reconhecido: Entenda os Absurdos do Direito",
  "YT-2024-07-12-Institucional_Pellizzetti_e_Walber_e_Associados_-_A_historia_por_tras_do_processo": "Institucional Pellizzetti e Walber e Associados: A história por trás do processo",
  "YT-2024-07-16-ERRO_da_Justica_-_Aposentadoria_Sem_Carencia_Apos_Mudanca_de_SEXO": "ERRO da Justiça: Aposentadoria Sem Carência Após Mudança de SEXO",
  "YT-2024-07-18-Entenda_como_funciona_APOSENTADORIA_ESPECIAL_do_SERVIDOR_PUBLICO": "Entenda como funciona APOSENTADORIA ESPECIAL do SERVIDOR PÚBLICO",
  "YT-2024-07-24-Vale_a_Pena_Indenizar_o_Tempo_Rural_para_Aposentadoria_no_RPPS": "Vale a Pena Indenizar o Tempo Rural para Aposentadoria no RPPS?",
  "YT-2024-07-25-Vale_a_Pena_Indenizar_o_Tempo_Rural_para_Aposentadoria_no_INSS": "Vale a Pena Indenizar o Tempo Rural para Aposentadoria no INSS?",
  "YT-2024-08-08-WhatsAppOrganizer_criando_uma_ferramenta_para_ajudar_os_advogados": "WhatsAppOrganizer criando uma ferramenta para ajudar os advogados",
  "YT-2024-08-09-Pontos_Controvertidos_ou_nao_e_Recontrovertidos_pelo_Magistrado": "Pontos Controvertidos (ou não) e Recontrovertidos pelo Magistrado",
  "YT-2024-08-13-Aposentadoria_Especial_sobre_niveis_de_RUIDOS_-_Parte_1_de_3": "Aposentadoria Especial sobre níveis de RUÍDOS - Parte 1 de 3",
  "YT-2024-08-15-Posso_receber_AUXILIO-ACIDENTE_e_DOENCA_ao_mesmo_tempo": "Posso receber AUXÍLIO-ACIDENTE e DOENÇA ao mesmo tempo?",
  "YT-2024-08-20-Tinha_tempo_Especial_e_nao_utilizei_na_minha_aposentadoria_-_E_agora": "Tinha tempo Especial e não utilizei na minha aposentadoria - E agora?",
  "YT-2024-08-22-EPI_contra_ruido_garante_APOSENTADORIA_ESPECIAL_Entenda_as_novas_regras_do_INSS_em_2024_-_Parte_2": "EPI contra ruído garante APOSENTADORIA ESPECIAL? Entenda as novas regras do INSS em 2024 - Parte 2",
  "YT-2024-08-27-Entenda_o_PERIODO_DE_GRACA_no_INSS_-_Seus_direitos_e_como_manter_a_qualidade_de_segurado": "Entenda o PERÍODO DE GRAÇA no INSS: Seus direitos e como manter a qualidade de segurado",
  "YT-2024-08-29-Entendendo_a_AVALIACAO_DE_RUIDOS_na_Aposentadoria_Especial_-_Parte_3": "Entendendo a AVALIAÇÃO DE RUÍDOS na Aposentadoria Especial - Parte 3",
  "YT-2024-09-11-Sumula_111_do_STJ_Confirmada_-_Mais_uma_decisao_que_prejudica_os_advogados_e_segurados": "Súmula 111 do STJ Confirmada - Mais uma decisão que prejudica os advogados e segurados",
  "YT-2024-09-24-Compra_e_Venda_de_Precatorios_Previdenciarios_E_outros_vale_a_pena": "Compra e Venda de Precatórios Previdenciários (E outros) vale a pena?",
  "YT-2024-09-24-Novidades_na_Aposentadoria_Complementar_do_Servidor_Publico_Paranaense_-_RPPS_Regime_Proprio": "Novidades na Aposentadoria Complementar do Servidor Público Paranaense - RPPS (Regime Próprio)",
  "YT-2024-09-25-Projudi_Crawler_-_Adicionando_Redundancia_nos_Sistemas_Judiciais": "Projudi Crawler - Adicionando Redundância nos Sistemas Judiciais",
  "YT-2024-09-26-Fim_e_Retorno_do_Minimo_Divisor_nas_Aposentadorias_do_INSS": "Fim e Retorno do Mínimo Divisor nas Aposentadorias do INSS",
  "YT-2024-10-01-Tema_1018_do_STJ_-_O_favoritos_dos_advogados_e_como_conseguir_os_dois_melhores_beneficios_do_INSS": "Tema 1018 do STJ - O favoritos dos advogados e como conseguir os dois melhores benefícios do INSS",
  "YT-2024-10-03-Pensao_por_Morte_-_Como_garantir_100%_do_Beneficio_Conceitos_que_podem_mudar_seu_beneficio": "Pensão por Morte: Como garantir 100% do Benefício? Conceitos que podem mudar seu benefício",
  "YT-2024-10-08-Injusto_entendimento_sobre_o_Militar_PM_que_migra_para_o_INSS_esta_sendo_alterado": "Injusto entendimento sobre o Militar (PM) que migra para o INSS está sendo alterado",
  "YT-2024-10-10-Pensao_por_Morte_Rural_e_um_pagamento_que_levou_ao_indeferimento_do_beneficio": "Pensão por Morte Rural e um pagamento que levou ao indeferimento do benefício",
  "YT-2024-10-15-Como_conseguir_e_discutir_a_validade_de_PPP_e_LTCAT_para_aposentadoria_especial_no_RPPS": "Como conseguir e discutir a validade de PPP e LTCAT para aposentadoria especial no RPPS",
  "YT-2024-10-17-ALERTA_Cuidado_ao_requerer_sua_pensao_por_morte_-_Extincao_nao_reversivel_das_cotas_apos_a_idade": "ALERTA! Cuidado ao requerer sua pensão por morte: Extinção não reversível das cotas apos a idade",
  "YT-2024-10-22-Desvio_de_funcao_no_RPPS_-_Quais_sao_as_consequencias": "Desvio de função no RPPS - Quais são as consequências?",
  "YT-2024-10-24-Pensao_por_Morte_e_Novo_casamento_no_INSS_e_no_RPPS_PR_-_Confira_suas_regras_para_nao_ter_surpresa": "Pensão por Morte e Novo casamento no INSS e no RPPS (PR) - Confira suas regras para não ter surpresa",
  "YT-2024-10-25-Tutorial_de_IA_-_Como_facilitar_seu_Dia-Dia_com_essa_Ferramenta_-_Introducao": "Tutorial de IA - Como facilitar seu Dia-Dia com essa Ferramenta - Introdução",
  "YT-2024-10-29-Recolhimento_em_Atraso_do_Socio_Quotista_-_Um_caso_unico_ou_uma_realidade": "Recolhimento em Atraso do Sócio Quotista - Um caso único ou uma realidade?",
  "YT-2024-10-31-Tutorial_-_Como_pedir_seu_auxilio_doenca_em_2024_Atualizado_Pelo_MEU_INSS_de_forma_gratuita_e_online": "Tutorial: Como pedir seu auxílio doença em 2024 Atualizado! Pelo MEU INSS de forma gratuita e online",
  "YT-2024-11-01-Tutorial_de_IA_-_Conceitos_basicos_e_como_superar_os_desafios_do_futuro": "Tutorial de IA: Conceitos básicos e como superar os desafios do futuro",
  "YT-2024-11-05-4_MENTIRAS_do_INSS_sobre_os_beneficios_previdenciarios": "4 MENTIRAS do INSS sobre os benefícios previdenciários",
  "YT-2024-11-12-CTC_-_Certidao_de_Tempo_de_Contribuicao_no_RPPS_para_fins_DECLARATORIOS_-_Cuidado_com_as_averbacoes": "CTC - Certidão de Tempo de Contribuição no RPPS  para fins DECLARATÓRIOS - Cuidado com as averbações",
  "YT-2024-11-14-Tutorial_-_Como_fazer_cumprimento_de_EXIGENCIA_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Tutorial: Como fazer cumprimento de EXIGÊNCIA pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2024-11-19-Noticia_Importante_RPPS_-_TCE_MG_admite_recebimento_de_Abono_de_Permanencia_e_o_Melhor_Beneficio": "Notícia Importante RPPS: TCE/MG admite recebimento de Abono de Permanência e o Melhor Benefício!",
  "YT-2024-11-21-4_Armadilhas_Previdenciarias_do_INSS_-_Fique_atento_aos_seus_direitos_para_nao_ter_surpresas_futuras": "4 Armadilhas Previdenciárias do INSS - Fique atento aos seus direitos para não ter surpresas futuras",
  "YT-2024-11-26-Como_funciona_a_Justica_Federal_Previdenciaria_e_como_isso_afeta_o_seu_pedido_de_aposentadoria": "Como funciona a Justiça Federal Previdenciária e como isso afeta o seu pedido de aposentadoria",
  "YT-2024-11-28-Boas_Noticias_-_Fim_da_Discussao_Sobre_o_Imposto_de_Renda_Fixo_em_25%_Brasileiro_no_Exterior": "Boas Notícias: Fim da Discussão Sobre o Imposto de Renda Fixo em 25% Brasileiro no Exterior!",
  "YT-2024-12-03-Noticia_-_Albino_Indigena_recebe_BPC_-_Entendendo_mais_sobre_beneficios_previdenciarios_e_incapacidade": "Notícia: Albino Indígena recebe BPC: Entendendo mais sobre benefícios previdenciários e incapacidade",
  "YT-2024-12-05-Tutorial_-_Per_DCOMP_Recolhimento_Incorreto_Servidor_Publico": "Tutorial: Per/DCOMP Recolhimento Incorreto Servidor Público",
  "YT-2024-12-10-Tutorial_-_Como_entrar_com_processo_sem_ADVOGADO_-_JUS_POSTULANDI": "Tutorial: Como entrar com processo sem ADVOGADO - JUS POSTULANDI",
  "YT-2024-12-12-Tutorial_-_Como_acessar_PPP_digital_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Tutorial: Como acessar PPP digital pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2025-01-07-Como_o_BENZENO_afeta_sua_saude_e_a_sua_aposentadoria_-_entenda_um_pouco_mais_sobre_este_elemento": "Como o BENZENO afeta sua saúde e a sua aposentadoria - entenda um pouco mais sobre este elemento",
  "YT-2025-01-09-Exposicao_a_agentes_Biologicos_e_Profissoes_Incomuns_-_entendendo_mais_sobre_aposentadoria_Especial": "Exposição a agentes Biológicos e Profissões Incomuns - entendendo mais sobre aposentadoria Especial",
  "YT-2025-01-14-Aposentadoria_Especial_do_Tecnico_de_Protese_Dentaria": "Aposentadoria Especial do Técnico de Prótese Dentária",
  "YT-2025-01-16-Conflitos_de_Deficiencias_-_qual_e_o_criterio_definitivo_para_a_Lei_e_para_a_Justica": "Conflitos de Deficiências: qual é o critério definitivo para a Lei e para a Justiça?",
  "YT-2025-01-21-Isencao_de_Imposto_de_Renda_e_Doencas_Graves_em_2025": "Isenção de Imposto de Renda e Doenças Graves em 2025",
  "YT-2025-01-23-Maior_Erro_do_Advogado_Previdenciario_-_Confiar_na_Contagem_Processual": "Maior Erro do Advogado Previdenciário: Confiar na Contagem Processual",
  "YT-2025-01-28-Isencao_Contribuicao_Previdenciaria_por_Doenca_Grave_-_um_Direito_Extinto_-_RPPS_PR": "Isenção Contribuição Previdenciária por Doença Grave - um Direito Extinto - RPPS PR",
  "YT-2025-01-29-Tutorial_de_IA_-_Entenda_o_que_e_um_modelo_e_como_a_inteligencia_da_IA_funciona": "Tutorial de IA: Entenda o que é um modelo e como a inteligência da IA funciona!",
  "YT-2025-01-30-como_fazer_REAJUSTE_das_contribuicoes_do_INSS_-_De_forma_ONLINE_e_SIMPLES": "como fazer REAJUSTE das contribuições do INSS - De forma ONLINE e SIMPLES",
  "YT-2025-02-05-Tutorial_de_IA_-_Como_navegar_no_mundo_da_IA_sem_se_perder_em_milhares_de_APLICATIVOS": "Tutorial de IA: Como navegar no mundo da IA sem se perder em milhares de APLICATIVOS",
  "YT-2025-02-06-Jovem_Advogado_-_Nunca_perda_o_sentimento_de_Justica_que_temos_no_primeiro_ano_da_faculdade": "Jovem Advogado: Nunca perda o sentimento de Justiça que temos no primeiro ano da faculdade",
  "YT-2025-02-11-Revisao_da_Vida_Toda_-_Cortes_e_Comentarios": "Revisão da Vida Toda - Cortes e Comentários",
  "YT-2025-02-12-Tutorial_de_IA_-_Como_API_Frontend_e_Backend_Funcionam_nos_Aplicativos_Modernos": "Tutorial de IA: Como API, Frontend e Backend Funcionam nos Aplicativos Modernos",
  "YT-2025-02-13-Aposentadoria_e_Ultimo_Salario_-_O_que_voce_precisa_saber": "Aposentadoria e Último Salário: O que você precisa saber",
  "YT-2025-02-18-Previdencia_e_aposentadoria_mudancas_do_INSS_em_2024_e_2025": "Previdência e aposentadoria mudanças do INSS em 2024 e 2025",
  "YT-2025-02-19-Tutorial_de_IA_-_O_que_e_uma_API_KEY_E_como_conseguir_sua_API_KEY_da_OpenAI_e_Claude": "Tutorial de IA: O que é uma API KEY? E como conseguir sua API KEY da OpenAI e Claude",
  "YT-2025-02-20-Beneficios_do_INSS_alem_da_Aposentadoria_e_Pensao_por_Morte_Voce_conhece_todos": "Benefícios do INSS além da Aposentadoria e Pensão por Morte! Você conhece todos?",
  "YT-2025-02-25-Como_evitar_erros_ao_pagar_o_INSS_No_comeco_do_ano_e_nao_prejudicar_sua_aposentadoria": "Como evitar erros ao pagar o INSS? No começo do ano e não prejudicar sua aposentadoria!",
  "YT-2025-02-26-Tutorial_de_IA_-_Os_principais_Players_do_mercado_da_Inteligencia_Artificial": "Tutorial de IA: Os principais Players do mercado da Inteligência Artificial!",
  "YT-2025-02-27-INSS_2025_-_Por_que_voce_NAO_vai_se_aposentar_pelo_teto_Uma_regra_de_calculo_inflacionario": "INSS 2025: Por que você NÃO vai se aposentar pelo teto? Uma regra de cálculo inflacionário",
  "YT-2025-03-05-Tutorial_de_IA_-_Assistentes_Agentes_IA_podem_otimizar_suas_tarefas": "Tutorial de IA: Assistentes/Agentes IA podem otimizar suas tarefas!",
  "YT-2025-03-11-Tutorial_-_Como_pedir_seu_auxilio_doenca_em_2025_pelo_MEU_INSS_de_forma_gratuita_online_e_rapida": "Tutorial: Como pedir seu auxílio doença em 2025 pelo MEU INSS, de forma gratuita, online e rápida",
  "YT-2025-03-12-Tutorial_de_IA_-_A_IA_tem_MEMORIA_Como_as_THREADS_ajudam_a_manter_o_contexto_das_respostas": "Tutorial de IA: A IA tem MEMÓRIA? Como as THREADS ajudam a manter o contexto das respostas",
  "YT-2025-03-13-Tutorial_-_Pedir_Aposentadoria_por_IDADE_em_2025_e_FACIL_com_o_MEU_INSS": "Tutorial: Pedir Aposentadoria por IDADE em 2025 é FÁCIL com o MEU INSS",
  "YT-2025-03-17-Prev_IA_-_O_Robo_Previdenciario_do_Parana_e_Realmente_Inteligente": "Prev IA: O Robô Previdenciário do Paraná é Realmente Inteligente?",
  "YT-2025-03-18-Aposentadoria_Especial_-_Como_comprovar_a_exposicao_a_vibracao": "Aposentadoria Especial: Como comprovar a exposição à vibração?",
  "YT-2025-03-19-Tutorial_de_IA_-_O_que_e_Fine_Tuning_e_como_ele_melhora_sua_IA": "Tutorial de IA: O que é Fine Tuning e como ele melhora sua IA",
  "YT-2025-03-20-Tutorial_-_Pesquisa_de_Jurisprudencia_para_Advogados_-_Como_agilizar_e_refinar_seus_resultados": "Tutorial: Pesquisa de Jurisprudência para Advogados - Como agilizar e refinar seus resultados",
  "YT-2025-03-25-Aposentadoria_Especial_-_Como_a_ineficacia_do_EPI_garantiu_a_VITORIA_neste_Caso": "Aposentadoria Especial: Como a ineficácia do EPI garantiu a VITÓRIA neste Caso",
};
